ecocampus/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ecocampus.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^consul/', include('consulquest.urls')),
    #url(r'^egafh/', include('egafh.urls')),
    url(r'^partage/', include('partage_app.urls', namespace='partage')),
    url(r'^admin/', include(admin.site.urls)),
)

partage_app/urls.py
from django.conf.urls import url
import  django_cas.views
from partage_app import views 

urlpatterns = [
    url(r'^index', views.index, name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^categories$', views.index,  {"sort": "category"}, name='index'),
    url(r'^lieux$', views.index,  {"sort": "location"}, name='index'),
    url(r'^ajouter$', views.add, name="add"),
    url(r'^enlever$', views.remove, name="remove"),
    url(r'^editer/(?P<obj_id>\d+)$', views.edit, name="edit"),
    #url(r'^admin/', include(admin.site.urls)),
    #url(r'^accounts/login/login/$', 'django_cas.views.login', name='login'),
    url(r'^accounts/login/$', 'django_cas.views.login', name='login'),
    url(r'^accounts/logout/$', 'django_cas.views.logout', name='logout'),
]

partage_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Location(models.Model):
    """ One of the ENS buildings"""
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=200)
    color =  models.CharField(max_length=9)

    def __unicode__(self):
        return self.name

class Shareable(models.Model):
    """ An object thar can be shared """
    


    NEED = 'demande'
    OFFER = 'propose'
    CLASS_CHOICES = (
        (NEED, 'demande'),
        (OFFER, 'propose'),
    )
    
    classe = models.CharField(max_length=10,
                              choices=CLASS_CHOICES,
                              default=NEED)

    name = models.CharField(max_length=200)
    
    details = models.CharField(max_length=1000)
    added = models.DateTimeField("date d'ajout")
    owner = models.ForeignKey(User)
    location = models.ForeignKey(Location)
    category = models.ForeignKey(Category)

    def __unicode__(self):
        return self.name

partage_app/views.py
#-*-coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponse,  HttpResponseRedirect
from django.template import RequestContext, loader
from partage_app import models
from django.utils import timezone

def index(request,msg=None,sort="category"):
    loc = models.Location.objects.all()
    categories = models.Category.objects.all()
    shareables = {} 
    
    context = {"locations":loc, 
               "categories":categories,
               "sort":sort,
               "msg":msg,
    }
    
    return render(request, 'partage_app/index.html', context)
    
def add(request):
    obj = models.Shareable(name=request.POST["name"],
                           details=request.POST["details"],
                           category=models.Category.objects.get(id=request.POST["category"]),
                           location=models.Location.objects.get(id=request.POST["location"]),
                           added=timezone.now(),
                           owner=models.User.objects.get(id=request.POST["user"]),
                           classe=request.POST["classe"],
    )
    obj.save()
    #return index(request)
    return HttpResponseRedirect(reverse('partage:index'))
    #return HttpResponseRedirect(".","OK.")

def remove(request):
    obj = models.Shareable.objects.get(id=request.POST["obj"])
    obj.delete()
    #return HttpResponseRedirect(".","OK.")
    #return render(reverse('partage:index'))
    return HttpResponseRedirect(reverse('partage:index'))

def edit(request, obj_id):
    obj = get_object_or_404(models.Shareable, id=obj_id)
    if request.method == "POST":
        user = models.User.objects.get(id=request.POST["user"])
        if obj.owner != user: # do checks again
            return HttpResponse("Il semblerait que vous ne soyez pas le propriétaire de l'objet en question...")
        obj.details = request.POST["details"]
        obj.name = request.POST["name"]
        obj.save()
        return HttpResponseRedirect(reverse('partage:index'))
        
    elif request.method == "GET":

        loc = models.Location.objects.all()
        categories = models.Category.objects.all()
    
        context = {"locations":loc, 
                   "categories":categories,
                   "obj":obj,
                   "owner": str(obj.owner)
                   }

        return render(request, 'partage_app/edit.html', context)
    #return HttpResponseRedirect(reverse('partage:index'))

partage_app/templates/partage_app/edit.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'partage_app/style.css' %}" />
  </head>
  <body>
    <h1> partage.ecocampus.ens.fr </h1>
    {% if user.is_authenticated %}
    <p>Votre identifiant clipper est <em>{{ user.username }}</em>.  <a href="{% url 'partage:logout' %}">Se déconnecter.</a> </p>

    {% if user.username == owner %}
    <h2> Modifier une annonce </h2>
    
    <form action="{% url 'partage:edit' obj.id %}"  method="post">
      {% csrf_token %}
      Nom de l'objet :  <input type="text" name="name" value="{{ obj.name }}" required/> <br />
      <input type="hidden" name="user" value="{{ user.id }}" /> 

      Informations suplémentaires:<br />
      <textarea name="details" rows="5" cols="50">{{ obj.details }}</textarea><br />

      <input type="submit" value="Modifier" />
    </form>
    {% else %}
    <p> Vous n'êtes pas autorisé.e à modifier cet objet qui appartient à {{ owner }}, il ne vous appartient pas </p>
    {% endif %}


    {% else %}
    <p>
      Bienvenue sur le système de partage d'objet proposé par Écocampus ! <br />
      <a href="{% url 'partage:login' %}">Connectez-vous</a> en utilisant vos identifiants clipper.
    </p>


    {% endif %}


</body>
</html>

partage_app/templates/partage_app/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'partage_app/style.css' %}" />

</head>
<body>

<h1> partage.ecocampus.ens.fr </h1>
{% if user.is_authenticated %}
    <p>Votre identifiant clipper est <em>{{ user.username }}</em>.  <a href="{% url 'partage:logout' %}">Se déconnecter.</a> </p>

    <div id="sort">Classer par :  <a href="categories">Categories</a> |  <a href="lieux">Lieux</a> </div>

{% if msg %}
{{msg}}
{% endif %}

{% if locations and sort == 'location' %}
	
    {% for loc in locations %}
	<div class="location">
        <h2> {{ loc.name }} </h2>
		{% for obj in loc.shareable_set.all %}
		<div class="shareable {{obj.classe}}">
		  <h3> {{ obj.name }} </h3>
		  		  <p>{{obj.details}}</p>
		  <p>Catégorie: {{obj.category}}. <em>L'utilisateur {{obj.owner.username}} {{obj.classe}} cet objet depuis le {{obj.added}}.</em></p>

		  <a href="mailto:{{obj.owner.username}}@clipper.ens.fr?subject=%5B%C3%89cocampus-partage%5D">Envoyer un courriel</a>
		  {% if obj.owner == user %}
<form action="enlever"  method="post">
{% csrf_token %}
		  <input type="hidden" name="obj" value="{{obj.id}}" />
		  <input type="submit" value="Retirer l'annonce" />
</form>
<form action="{% url 'partage:edit' obj.id %}">
		  <input type="submit" value="Éditer l'annonce" />
</form>
		  {% endif %}

		</div>

		{% endfor %}

	</div>
    {% endfor %}

{% elif categories and sort == 'category' %}
    {% for cat in categories %}
	<div class="category">
        <h2> {{ cat.name }} </h2>
		{% for obj in cat.shareable_set.all %}
		<div class="shareable {{obj.classe}}">
          <h3> {{ obj.name }} </h3>
		  <p>{{obj.details}}</p>
	          <p>Lieu: {{obj.location}}. <em>L'utilisateur {{obj.owner.username}} {{obj.classe}} cet objet depuis le {{obj.added}}.</em></p>

		  <a href="mailto:{{obj.owner.username}}@clipper.ens.fr?subject=%5B%C3%89cocampus-partage%5D">Envoyer un courriel</a>

		  {% if obj.owner == user %}
<form action="enlever"  method="post">
{% csrf_token %}
		  <input type="hidden" name="obj" value="{{obj.id}}" />
		  <input type="submit" value="Retirer l'annonce" />
</form>
<form action="{% url 'partage:edit' obj.id %}">
		  <input type="submit" value="Éditer l'annonce" />
</form>

		  {% endif %}
		</div>
		{% endfor %}

	</div>
    {% endfor %}


{% else %}
    <p>Aucun lieu enregistré</p>
{% endif %}



<h2> Ajouter une annonce </h2>
<form action="ajouter"  method="post">
{% csrf_token %}
Nom de l'objet  :  <input type="text" name="name" required/> <br />
<input type="hidden" name="user" value="{{ user.id }}" /> 

<input type="radio" name="classe" value="demande" checked /> Demande 
<input type="radio" name="classe" value="propose" /> Propose <br />

Lieu :
<select name="location">

{% for loc in locations %}
<option value="{{ loc.id }}">{{ loc.name }}</option> 
{% endfor %}
</select> <br />
Catégorie : 
<select name="category">
{% for cat in categories %}
<option value="{{ cat.id }}">{{ cat.name }}</option> 
{% endfor %}
</select> <br />


Informations suplémentaires:<br />
<textarea name="details" rows="5" cols="50"></textarea><br />


<input type="submit" value="Ajouter" />
</form>


{% else %}
    <p>Bienvenue sur le système de partage d'objet proposé par Écocampus ! <br />
	<a href="{% url 'partage:login' %}">Connectez-vous</a> en utilisant vos identifiants clipper.</p>


{% endif %}


</body>
</html>